CREATE TABLE IF NOT EXISTS entity_record (
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(120) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_entity_record_type_updated
    ON entity_record(entity_type, updated_at);

CREATE TABLE IF NOT EXISTS telemetry (
    event_id VARCHAR(160) PRIMARY KEY,
    farm_id VARCHAR(120) NOT NULL,
    plot_id VARCHAR(120) NOT NULL,
    device_id VARCHAR(120) NOT NULL,
    metric VARCHAR(80) NOT NULL,
    metric_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(40) NOT NULL,
    event_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    quality_status VARCHAR(40) NOT NULL,
    quality_json TEXT NOT NULL,
    scenario_id VARCHAR(160),
    branch_id VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_telemetry_plot_metric_ts
    ON telemetry(plot_id, metric, event_ts);

CREATE TABLE IF NOT EXISTS event_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(120) NOT NULL,
    event_id VARCHAR(160),
    trace_id VARCHAR(160),
    scenario_id VARCHAR(160),
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_log_trace_created
    ON event_log(trace_id, created_at);

CREATE TABLE IF NOT EXISTS idempotency_key (
    idempotency_key VARCHAR(200) PRIMARY KEY,
    command_id VARCHAR(160) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_account (
    user_id VARCHAR(120) PRIMARY KEY,
    username VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_code VARCHAR(60) NOT NULL,
    farm_ids TEXT NOT NULL,
    plot_ids TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
