server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;
    client_max_body_size 40m;

    location /api/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
    }

    location /actuator/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /v3/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /swagger-ui/ {
        proxy_pass http://api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /v1/ { return 404; }

    location = / { return 302 /agriloop/; }
    location = /agriloop { return 301 /agriloop/; }
    location = /agriloop/ { rewrite ^ /index.html last; }
    location /agriloop/ {
        rewrite ^/agriloop/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /login { return 301 /login/; }
    location = /login/ { rewrite ^ /login.html last; }
    location /login/ {
        rewrite ^/login/(.*)$ /$1 break;
        try_files $uri $uri/ /login.html;
    }

    location = /farm-admin { return 301 /farm-admin/; }
    location = /farm-admin/ { rewrite ^ /index.html last; }
    location /farm-admin/ {
        rewrite ^/farm-admin/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /farmer { return 301 /farmer/; }
    location = /farmer/ { rewrite ^ /farmer.html last; }
    location /farmer/ {
        rewrite ^/farmer/(.*)$ /$1 break;
        try_files $uri $uri/ /farmer.html;
    }

    location = /system-admin { return 301 /system-admin/; }
    location = /system-admin/ { rewrite ^ /sysadmin.html last; }
    location /system-admin/ {
        rewrite ^/system-admin/(.*)$ /$1 break;
        try_files $uri $uri/ /sysadmin.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
