package com.agriloop;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.http.HttpHeaders;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.List;
import java.util.Map;

@Component
class JwtAuthenticationFilter extends OncePerRequestFilter {
    private final JwtService jwtService;
    private final AgriStore store;
    JwtAuthenticationFilter(JwtService jwtService, AgriStore store) { this.jwtService = jwtService; this.store = store; }

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws ServletException, IOException {
        String header = request.getHeader(HttpHeaders.AUTHORIZATION);
        if (header != null && header.startsWith("Bearer ")) {
            try {
                UserPrincipal principal = jwtService.parse(header.substring(7));
                if (!store.credentialVersionMatches(principal.userId, principal.credentialVersion)) throw new IllegalArgumentException("credential version mismatch");
                // Scope is deliberately reloaded for every protected request.
                // Tokens retain the same schema, while a farm manager's scope
                // revocation becomes effective immediately.
                Map<String, Object> current = store.userById(principal.userId);
                if (current == null || !Jsons.bool(current, "enabled", true)) throw new IllegalArgumentException("account disabled");
                UserPrincipal effective = new UserPrincipal(principal.userId,
                        Jsons.text(current, "username", principal.username),
                        Jsons.text(current, "role", principal.role),
                        Jsons.strings(current.get("farmIds")), Jsons.strings(current.get("plotIds")),
                        principal.credentialVersion);
                List<GrantedAuthority> authorities = List.of(new SimpleGrantedAuthority("ROLE_" + effective.role));
                SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(effective, null, authorities));
            } catch (Exception ignored) {
                // The controller will return the standard 401 generated by Spring Security.
            }
        }
        chain.doFilter(request, response);
    }
}
